// scripts/icList.ts
export type IcSeed = {
  id: string;
  name: string;
  roadId: string;
  roadName: string;
  isSmart: boolean;
  etcOnly: boolean;
  entranceAvailable: boolean;
  exitAvailable: boolean;
  area: string;
  directionGroup: string;
  prevIcId?: string;
  nextIcId?: string;
  junctionPrevIcId?: string;
  junctionNextIcId?: string;
  availableHours: string;
  notes?: string;
  geocodeQuery: string; // Google Geocoding に渡すクエリ
};

export const IC_LIST: IcSeed[] = [
  // ========== 東名高速道路 ==========
  { id: "tomei_tokyo", name: "東京IC", roadId: "tomei", roadName: "東名高速道路", isSmart: false, etcOnly: false, entranceAvailable: true, exitAvailable: true, area: "東京都世田谷区", directionGroup: "shizuoka", nextIcId: "tomei_kawasaki", availableHours: "24h", geocodeQuery: "東名高速道路 東京インターチェンジ 世田谷区" },
  { id: "tomei_kawasaki", name: "東名川崎IC", roadId: "tomei", roadName: "東名高速道路", isSmart: false, etcOnly: false, entranceAvailable: true, exitAvailable: true, area: "神奈川県川崎市", directionGroup: "shizuoka", prevIcId: "tomei_tokyo", nextIcId: "tomei_yokohama_aoba", availableHours: "24h", geocodeQuery: "東名川崎インターチェンジ 東名高速道路" },
  { id: "tomei_yokohama_aoba", name: "横浜青葉IC", roadId: "tomei", roadName: "東名高速道路", isSmart: false, etcOnly: false, entranceAvailable: true, exitAvailable: true, area: "神奈川県横浜市", directionGroup: "shizuoka", prevIcId: "tomei_kawasaki", nextIcId: "tomei_yokohama_machida", availableHours: "24h", geocodeQuery: "横浜青葉インターチェンジ 東名高速道路" },
  { id: "tomei_yokohama_machida", name: "横浜町田IC", roadId: "tomei", roadName: "東名高速道路", isSmart: false, etcOnly: false, entranceAvailable: true, exitAvailable: true, area: "神奈川県横浜市", directionGroup: "shizuoka", prevIcId: "tomei_yokohama_aoba", nextIcId: "tomei_atsugi", availableHours: "24h", geocodeQuery: "横浜町田インターチェンジ 東名高速道路" },
  { id: "tomei_atsugi", name: "厚木IC", roadId: "tomei", roadName: "東名高速道路", isSmart: false, etcOnly: false, entranceAvailable: true, exitAvailable: true, area: "神奈川県厚木市", directionGroup: "shizuoka", prevIcId: "tomei_yokohama_machida", nextIcId: "tomei_hadano_nakai", availableHours: "24h", geocodeQuery: "厚木インターチェンジ 東名高速道路" },
  { id: "tomei_hadano_nakai", name: "秦野中井IC", roadId: "tomei", roadName: "東名高速道路", isSmart: false, etcOnly: false, entranceAvailable: true, exitAvailable: true, area: "神奈川県秦野市", directionGroup: "shizuoka", prevIcId: "tomei_atsugi", nextIcId: "tomei_oiwa_matsuda", availableHours: "24h", geocodeQuery: "秦野中井インターチェンジ 東名高速道路" },
  { id: "tomei_oiwa_matsuda", name: "大井松田IC", roadId: "tomei", roadName: "東名高速道路", isSmart: false, etcOnly: false, entranceAvailable: true, exitAvailable: true, area: "神奈川県足柄上郡大井町", directionGroup: "shizuoka", prevIcId: "tomei_hadano_nakai", nextIcId: "tomei_gotemba", availableHours: "24h", geocodeQuery: "大井松田インターチェンジ 東名高速道路" },
  { id: "tomei_gotemba", name: "御殿場IC", roadId: "tomei", roadName: "東名高速道路", isSmart: false, etcOnly: false, entranceAvailable: true, exitAvailable: true, area: "静岡県御殿場市", directionGroup: "shizuoka", prevIcId: "tomei_oiwa_matsuda", nextIcId: "tomei_susono", availableHours: "24h", geocodeQuery: "御殿場インターチェンジ 東名高速道路" },
  { id: "tomei_susono", name: "裾野IC", roadId: "tomei", roadName: "東名高速道路", isSmart: false, etcOnly: false, entranceAvailable: true, exitAvailable: true, area: "静岡県裾野市", directionGroup: "shizuoka", prevIcId: "tomei_gotemba", nextIcId: "tomei_numazu", availableHours: "24h", geocodeQuery: "裾野インターチェンジ 東名高速道路" },
  { id: "tomei_numazu", name: "沼津IC", roadId: "tomei", roadName: "東名高速道路", isSmart: false, etcOnly: false, entranceAvailable: true, exitAvailable: true, area: "静岡県沼津市", directionGroup: "shizuoka", prevIcId: "tomei_susono", nextIcId: "tomei_fuji", availableHours: "24h", geocodeQuery: "沼津インターチェンジ 東名高速道路" },
  { id: "tomei_fuji", name: "富士IC", roadId: "tomei", roadName: "東名高速道路", isSmart: false, etcOnly: false, entranceAvailable: true, exitAvailable: true, area: "静岡県富士市", directionGroup: "shizuoka", prevIcId: "tomei_numazu", nextIcId: "tomei_shimizu", availableHours: "24h", geocodeQuery: "富士インターチェンジ 東名高速道路 静岡県" },
  { id: "tomei_shimizu", name: "清水IC", roadId: "tomei", roadName: "東名高速道路", isSmart: false, etcOnly: false, entranceAvailable: true, exitAvailable: true, area: "静岡県静岡市清水区", directionGroup: "shizuoka", prevIcId: "tomei_fuji", nextIcId: "tomei_nihondaira_kunozan_smart", availableHours: "24h", notes: "清水区・清水港方面", geocodeQuery: "清水インターチェンジ 東名高速道路 静岡市" },
  { id: "tomei_nihondaira_kunozan_smart", name: "日本平久能山スマートIC", roadId: "tomei", roadName: "東名高速道路", isSmart: true, etcOnly: true, entranceAvailable: true, exitAvailable: true, area: "静岡県静岡市駿河区", directionGroup: "shizuoka", prevIcId: "tomei_shimizu", nextIcId: "tomei_shizuoka", availableHours: "24h", notes: "ETC専用。日本平・久能山方面", geocodeQuery: "日本平久能山スマートインターチェンジ 東名高速道路" },
  { id: "tomei_shizuoka", name: "静岡IC", roadId: "tomei", roadName: "東名高速道路", isSmart: false, etcOnly: false, entranceAvailable: true, exitAvailable: true, area: "静岡県静岡市", directionGroup: "shizuoka", prevIcId: "tomei_nihondaira_kunozan_smart", availableHours: "24h", notes: "静岡市中心部・駿河区方面", geocodeQuery: "静岡インターチェンジ 東名高速道路" },

  // ========== 新東名高速道路 ==========
  { id: "shin_tomei_ebina_minami", name: "海老名南JCT", roadId: "shin_tomei", roadName: "新東名高速道路", isSmart: false, etcOnly: false, entranceAvailable: false, exitAvailable: false, area: "神奈川県海老名市", directionGroup: "shizuoka", nextIcId: "shin_tomei_atsugi_minami", availableHours: "24h", notes: "JCTのみ（ICなし）", geocodeQuery: "海老名南ジャンクション 新東名高速道路" },
  { id: "shin_tomei_atsugi_minami", name: "厚木南IC", roadId: "shin_tomei", roadName: "新東名高速道路", isSmart: false, etcOnly: false, entranceAvailable: true, exitAvailable: true, area: "神奈川県厚木市", directionGroup: "shizuoka", prevIcId: "shin_tomei_ebina_minami", nextIcId: "shin_tomei_isehara_oyama", availableHours: "24h", geocodeQuery: "厚木南インターチェンジ 新東名高速道路" },
  { id: "shin_tomei_isehara_oyama", name: "伊勢原大山IC", roadId: "shin_tomei", roadName: "新東名高速道路", isSmart: false, etcOnly: false, entranceAvailable: true, exitAvailable: true, area: "神奈川県伊勢原市", directionGroup: "shizuoka", prevIcId: "shin_tomei_atsugi_minami", nextIcId: "shin_tomei_hadano_tanzawa", availableHours: "24h", geocodeQuery: "伊勢原大山インターチェンジ 新東名高速道路" },
  { id: "shin_tomei_hadano_tanzawa", name: "秦野丹沢IC", roadId: "shin_tomei", roadName: "新東名高速道路", isSmart: false, etcOnly: false, entranceAvailable: true, exitAvailable: true, area: "神奈川県秦野市", directionGroup: "shizuoka", prevIcId: "shin_tomei_isehara_oyama", nextIcId: "shin_tomei_shin_gotemba", availableHours: "24h", geocodeQuery: "秦野丹沢スマートインターチェンジ 新東名高速道路" },
  { id: "shin_tomei_shin_gotemba", name: "新御殿場IC", roadId: "shin_tomei", roadName: "新東名高速道路", isSmart: false, etcOnly: false, entranceAvailable: true, exitAvailable: true, area: "静岡県御殿場市", directionGroup: "shizuoka", prevIcId: "shin_tomei_hadano_tanzawa", nextIcId: "shin_tomei_nagaizumi_numazu", availableHours: "24h", geocodeQuery: "新御殿場インターチェンジ 新東名高速道路" },
  { id: "shin_tomei_nagaizumi_numazu", name: "長泉沼津IC", roadId: "shin_tomei", roadName: "新東名高速道路", isSmart: false, etcOnly: false, entranceAvailable: true, exitAvailable: true, area: "静岡県駿東郡長泉町", directionGroup: "shizuoka", prevIcId: "shin_tomei_shin_gotemba", nextIcId: "shin_tomei_shin_fuji", availableHours: "24h", geocodeQuery: "長泉沼津インターチェンジ 新東名高速道路" },
  { id: "shin_tomei_shin_fuji", name: "新富士IC", roadId: "shin_tomei", roadName: "新東名高速道路", isSmart: false, etcOnly: false, entranceAvailable: true, exitAvailable: true, area: "静岡県富士市", directionGroup: "shizuoka", prevIcId: "shin_tomei_nagaizumi_numazu", nextIcId: "shin_tomei_shimizu_ihara", availableHours: "24h", geocodeQuery: "新富士インターチェンジ 新東名高速道路" },
  { id: "shin_tomei_shimizu_ihara", name: "清水いはらIC", roadId: "shin_tomei", roadName: "新東名高速道路", isSmart: false, etcOnly: false, entranceAvailable: true, exitAvailable: true, area: "静岡県静岡市清水区", directionGroup: "shizuoka", prevIcId: "shin_tomei_shin_fuji", nextIcId: "shin_tomei_shin_shimizu", availableHours: "24h", geocodeQuery: "清水いはらインターチェンジ 新東名高速道路" },
  { id: "shin_tomei_shin_shimizu", name: "新清水IC", roadId: "shin_tomei", roadName: "新東名高速道路", isSmart: false, etcOnly: false, entranceAvailable: true, exitAvailable: true, area: "静岡県静岡市清水区", directionGroup: "shizuoka", prevIcId: "shin_tomei_shimizu_ihara", nextIcId: "shin_tomei_shizuoka_sa_smart", availableHours: "24h", notes: "清水区北部方面", geocodeQuery: "新清水インターチェンジ 新東名高速道路" },
  { id: "shin_tomei_shizuoka_sa_smart", name: "静岡SAスマートIC", roadId: "shin_tomei", roadName: "新東名高速道路", isSmart: true, etcOnly: true, entranceAvailable: true, exitAvailable: true, area: "静岡県静岡市葵区", directionGroup: "shizuoka", prevIcId: "shin_tomei_shin_shimizu", nextIcId: "shin_tomei_shin_shizuoka", availableHours: "24h", notes: "ETC専用。新東名側", geocodeQuery: "静岡サービスエリアスマートインターチェンジ 新東名高速道路" },
  { id: "shin_tomei_shin_shizuoka", name: "新静岡IC", roadId: "shin_tomei", roadName: "新東名高速道路", isSmart: false, etcOnly: false, entranceAvailable: true, exitAvailable: true, area: "静岡県静岡市葵区", directionGroup: "shizuoka", prevIcId: "shin_tomei_shizuoka_sa_smart", availableHours: "24h", notes: "静岡市北側・葵区方面", geocodeQuery: "新静岡インターチェンジ 新東名高速道路" },

  // ========== 東北自動車道 ==========
  { id: "tohoku_kawaguchi", name: "川口IC", roadId: "tohoku", roadName: "東北自動車道", isSmart: false, etcOnly: false, entranceAvailable: true, exitAvailable: true, area: "埼玉県川口市", directionGroup: "shizuoka", nextIcId: "tohoku_urawa", junctionPrevIcId: "gaikan_oizumi", availableHours: "24h", notes: "東北道の南端、川口JCTで首都高/外環接続", geocodeQuery: "川口インターチェンジ 東北自動車道" },
  { id: "tohoku_urawa", name: "浦和IC", roadId: "tohoku", roadName: "東北自動車道", isSmart: false, etcOnly: false, entranceAvailable: true, exitAvailable: true, area: "埼玉県さいたま市", directionGroup: "shizuoka", prevIcId: "tohoku_kawaguchi", nextIcId: "tohoku_iwatsuki", availableHours: "24h", geocodeQuery: "浦和インターチェンジ 東北自動車道" },
  { id: "tohoku_iwatsuki", name: "岩槻IC", roadId: "tohoku", roadName: "東北自動車道", isSmart: false, etcOnly: false, entranceAvailable: true, exitAvailable: true, area: "埼玉県さいたま市岩槻区", directionGroup: "shizuoka", prevIcId: "tohoku_urawa", nextIcId: "tohoku_kuki", availableHours: "24h", geocodeQuery: "岩槻インターチェンジ 東北自動車道" },
  { id: "tohoku_kuki", name: "久喜IC", roadId: "tohoku", roadName: "東北自動車道", isSmart: false, etcOnly: false, entranceAvailable: true, exitAvailable: true, area: "埼玉県久喜市", directionGroup: "shizuoka", prevIcId: "tohoku_iwatsuki", nextIcId: "tohoku_kazo", availableHours: "24h", geocodeQuery: "久喜インターチェンジ 東北自動車道" },
  { id: "tohoku_kazo", name: "加須IC", roadId: "tohoku", roadName: "東北自動車道", isSmart: false, etcOnly: false, entranceAvailable: true, exitAvailable: true, area: "埼玉県加須市", directionGroup: "shizuoka", prevIcId: "tohoku_kuki", nextIcId: "tohoku_hanyu", availableHours: "24h", geocodeQuery: "加須インターチェンジ 東北自動車道" },
  { id: "tohoku_hanyu", name: "羽生IC", roadId: "tohoku", roadName: "東北自動車道", isSmart: false, etcOnly: false, entranceAvailable: true, exitAvailable: true, area: "埼玉県羽生市", directionGroup: "shizuoka", prevIcId: "tohoku_kazo", nextIcId: "tohoku_tatebayashi", availableHours: "24h", geocodeQuery: "羽生インターチェンジ 東北自動車道" },
  { id: "tohoku_tatebayashi", name: "館林IC", roadId: "tohoku", roadName: "東北自動車道", isSmart: false, etcOnly: false, entranceAvailable: true, exitAvailable: true, area: "群馬県館林市", directionGroup: "shizuoka", prevIcId: "tohoku_hanyu", nextIcId: "tohoku_sano_fujioka", availableHours: "24h", geocodeQuery: "館林インターチェンジ 東北自動車道" },
  { id: "tohoku_sano_fujioka", name: "佐野藤岡IC", roadId: "tohoku", roadName: "東北自動車道", isSmart: false, etcOnly: false, entranceAvailable: true, exitAvailable: true, area: "栃木県佐野市", directionGroup: "shizuoka", prevIcId: "tohoku_tatebayashi", nextIcId: "tohoku_sano_sa_smart", availableHours: "24h", geocodeQuery: "佐野藤岡インターチェンジ 東北自動車道" },
  { id: "tohoku_sano_sa_smart", name: "佐野SAスマートIC", roadId: "tohoku", roadName: "東北自動車道", isSmart: true, etcOnly: true, entranceAvailable: true, exitAvailable: true, area: "栃木県佐野市", directionGroup: "shizuoka", prevIcId: "tohoku_sano_fujioka", nextIcId: "tohoku_tochigi", availableHours: "24h", notes: "ETC専用", geocodeQuery: "佐野サービスエリアスマートインターチェンジ 東北自動車道" },
  { id: "tohoku_tochigi", name: "栃木IC", roadId: "tohoku", roadName: "東北自動車道", isSmart: false, etcOnly: false, entranceAvailable: true, exitAvailable: true, area: "栃木県栃木市", directionGroup: "shizuoka", prevIcId: "tohoku_sano_sa_smart", availableHours: "24h", geocodeQuery: "栃木インターチェンジ 東北自動車道" },
  { id: "tohoku_utsunomiya", name: "宇都宮IC", roadId: "tohoku", roadName: "東北自動車道", isSmart: false, etcOnly: false, entranceAvailable: true, exitAvailable: true, area: "栃木県宇都宮市", directionGroup: "shizuoka", availableHours: "24h", geocodeQuery: "宇都宮インターチェンジ 東北自動車道" },
  { id: "tohoku_yaita", name: "矢板IC", roadId: "tohoku", roadName: "東北自動車道", isSmart: false, etcOnly: false, entranceAvailable: true, exitAvailable: true, area: "栃木県矢板市", directionGroup: "shizuoka", availableHours: "24h", geocodeQuery: "矢板インターチェンジ 東北自動車道" },
  { id: "tohoku_nasu", name: "那須IC", roadId: "tohoku", roadName: "東北自動車道", isSmart: false, etcOnly: false, entranceAvailable: true, exitAvailable: true, area: "栃木県那須郡那須町", directionGroup: "shizuoka", availableHours: "24h", geocodeQuery: "那須インターチェンジ 東北自動車道" },
  { id: "tohoku_shirakawa", name: "白河IC", roadId: "tohoku", roadName: "東北自動車道", isSmart: false, etcOnly: false, entranceAvailable: true, exitAvailable: true, area: "福島県白河市", directionGroup: "shizuoka", availableHours: "24h", geocodeQuery: "白河インターチェンジ 東北自動車道" },
  { id: "tohoku_koriyama", name: "郡山IC", roadId: "tohoku", roadName: "東北自動車道", isSmart: false, etcOnly: false, entranceAvailable: true, exitAvailable: true, area: "福島県郡山市", directionGroup: "shizuoka", availableHours: "24h", geocodeQuery: "郡山インターチェンジ 東北自動車道" },
  { id: "tohoku_fukushima_nishi", name: "福島西IC", roadId: "tohoku", roadName: "東北自動車道", isSmart: false, etcOnly: false, entranceAvailable: true, exitAvailable: true, area: "福島県福島市", directionGroup: "shizuoka", availableHours: "24h", geocodeQuery: "福島西インターチェンジ 東北自動車道" },
  { id: "tohoku_shiroishi", name: "白石IC", roadId: "tohoku", roadName: "東北自動車道", isSmart: false, etcOnly: false, entranceAvailable: true, exitAvailable: true, area: "宮城県白石市", directionGroup: "shizuoka", availableHours: "24h", geocodeQuery: "白石インターチェンジ 東北自動車道" },
  { id: "tohoku_sendai_minami", name: "仙台南IC", roadId: "tohoku", roadName: "東北自動車道", isSmart: false, etcOnly: false, entranceAvailable: true, exitAvailable: true, area: "宮城県仙台市太白区", directionGroup: "shizuoka", availableHours: "24h", geocodeQuery: "仙台南インターチェンジ 東北自動車道" },
  { id: "tohoku_sendai_miyagi", name: "仙台宮城IC", roadId: "tohoku", roadName: "東北自動車道", isSmart: false, etcOnly: false, entranceAvailable: true, exitAvailable: true, area: "宮城県仙台市青葉区", directionGroup: "shizuoka", availableHours: "24h", geocodeQuery: "仙台宮城インターチェンジ 東北自動車道" },
  { id: "tohoku_izumi", name: "泉IC", roadId: "tohoku", roadName: "東北自動車道", isSmart: false, etcOnly: false, entranceAvailable: true, exitAvailable: true, area: "宮城県仙台市泉区", directionGroup: "shizuoka", availableHours: "24h", geocodeQuery: "泉インターチェンジ 東北自動車道 仙台市泉区" },
  { id: "tohoku_furukawa", name: "古川IC", roadId: "tohoku", roadName: "東北自動車道", isSmart: false, etcOnly: false, entranceAvailable: true, exitAvailable: true, area: "宮城県大崎市", directionGroup: "shizuoka", availableHours: "24h", geocodeQuery: "古川インターチェンジ 東北自動車道 大崎市" },
  { id: "tohoku_wakayagi_kanari", name: "若柳金成IC", roadId: "tohoku", roadName: "東北自動車道", isSmart: false, etcOnly: false, entranceAvailable: true, exitAvailable: true, area: "宮城県栗原市", directionGroup: "shizuoka", availableHours: "24h", geocodeQuery: "若柳金成インターチェンジ 東北自動車道" },
  { id: "tohoku_ichinoseki", name: "一関IC", roadId: "tohoku", roadName: "東北自動車道", isSmart: false, etcOnly: false, entranceAvailable: true, exitAvailable: true, area: "岩手県一関市", directionGroup: "shizuoka", availableHours: "24h", geocodeQuery: "一関インターチェンジ 東北自動車道" },
  { id: "tohoku_mizusawa", name: "水沢IC", roadId: "tohoku", roadName: "東北自動車道", isSmart: false, etcOnly: false, entranceAvailable: true, exitAvailable: true, area: "岩手県奥州市", directionGroup: "shizuoka", availableHours: "24h", geocodeQuery: "水沢インターチェンジ 東北自動車道 岩手県奥州市" },
  { id: "tohoku_kitakami", name: "北上IC", roadId: "tohoku", roadName: "東北自動車道", isSmart: false, etcOnly: false, entranceAvailable: true, exitAvailable: true, area: "岩手県北上市", directionGroup: "shizuoka", availableHours: "24h", geocodeQuery: "北上インターチェンジ 東北自動車道" },
  { id: "tohoku_hanamaki", name: "花巻IC", roadId: "tohoku", roadName: "東北自動車道", isSmart: false, etcOnly: false, entranceAvailable: true, exitAvailable: true, area: "岩手県花巻市", directionGroup: "shizuoka", availableHours: "24h", geocodeQuery: "花巻インターチェンジ 東北自動車道" },
  { id: "tohoku_morioka", name: "盛岡IC", roadId: "tohoku", roadName: "東北自動車道", isSmart: false, etcOnly: false, entranceAvailable: true, exitAvailable: true, area: "岩手県盛岡市", directionGroup: "shizuoka", availableHours: "24h", geocodeQuery: "盛岡インターチェンジ 東北自動車道" },
  { id: "tohoku_takizawa", name: "滝沢IC", roadId: "tohoku", roadName: "東北自動車道", isSmart: false, etcOnly: false, entranceAvailable: true, exitAvailable: true, area: "岩手県滝沢市", directionGroup: "shizuoka", availableHours: "24h", geocodeQuery: "滝沢インターチェンジ 東北自動車道" },
  { id: "tohoku_ashiro", name: "安代IC", roadId: "tohoku", roadName: "東北自動車道", isSmart: false, etcOnly: false, entranceAvailable: true, exitAvailable: true, area: "岩手県八幡平市", directionGroup: "shizuoka", availableHours: "24h", geocodeQuery: "安代インターチェンジ 東北自動車道 八幡平市" },
  { id: "tohoku_kosaka", name: "小坂IC", roadId: "tohoku", roadName: "東北自動車道", isSmart: false, etcOnly: false, entranceAvailable: true, exitAvailable: true, area: "秋田県小坂町", directionGroup: "shizuoka", availableHours: "24h", geocodeQuery: "小坂インターチェンジ 東北自動車道 秋田県" },
  { id: "tohoku_owani_hirosaki", name: "大鰐弘前IC", roadId: "tohoku", roadName: "東北自動車道", isSmart: false, etcOnly: false, entranceAvailable: true, exitAvailable: true, area: "青森県大鰐町", directionGroup: "shizuoka", availableHours: "24h", geocodeQuery: "大鰐弘前インターチェンジ 東北自動車道" },
  { id: "tohoku_aomori", name: "青森IC", roadId: "tohoku", roadName: "東北自動車道", isSmart: false, etcOnly: false, entranceAvailable: true, exitAvailable: true, area: "青森県青森市", directionGroup: "shizuoka", availableHours: "24h", geocodeQuery: "青森インターチェンジ 東北自動車道" },

  // ========== 関越自動車道 ==========
  { id: "kanetsu_nerima", name: "練馬IC", roadId: "kanetsu", roadName: "関越自動車道", isSmart: false, etcOnly: false, entranceAvailable: true, exitAvailable: true, area: "東京都練馬区", directionGroup: "shizuoka", nextIcId: "kanetsu_tokorozawa", availableHours: "24h", notes: "関越自動車道の東京側起点", geocodeQuery: "練馬インターチェンジ 関越自動車道" },
  { id: "kanetsu_tokorozawa", name: "所沢IC", roadId: "kanetsu", roadName: "関越自動車道", isSmart: false, etcOnly: false, entranceAvailable: true, exitAvailable: true, area: "埼玉県所沢市", directionGroup: "shizuoka", prevIcId: "kanetsu_nerima", nextIcId: "kanetsu_kawagoe", availableHours: "24h", geocodeQuery: "所沢インターチェンジ 関越自動車道" },
  { id: "kanetsu_kawagoe", name: "川越IC", roadId: "kanetsu", roadName: "関越自動車道", isSmart: false, etcOnly: false, entranceAvailable: true, exitAvailable: true, area: "埼玉県川越市", directionGroup: "shizuoka", prevIcId: "kanetsu_tokorozawa", nextIcId: "kanetsu_tsurugashima", availableHours: "24h", geocodeQuery: "川越インターチェンジ 関越自動車道" },
  { id: "kanetsu_tsurugashima", name: "鶴ヶ島IC", roadId: "kanetsu", roadName: "関越自動車道", isSmart: false, etcOnly: false, entranceAvailable: true, exitAvailable: true, area: "埼玉県鶴ヶ島市", directionGroup: "shizuoka", prevIcId: "kanetsu_kawagoe", nextIcId: "kanetsu_higashi_matsuyama", availableHours: "24h", geocodeQuery: "鶴ヶ島インターチェンジ 関越自動車道" },
  { id: "kanetsu_higashi_matsuyama", name: "東松山IC", roadId: "kanetsu", roadName: "関越自動車道", isSmart: false, etcOnly: false, entranceAvailable: true, exitAvailable: true, area: "埼玉県東松山市", directionGroup: "shizuoka", prevIcId: "kanetsu_tsurugashima", nextIcId: "kanetsu_hanazono", availableHours: "24h", geocodeQuery: "東松山インターチェンジ 関越自動車道" },
  { id: "kanetsu_hanazono", name: "花園IC", roadId: "kanetsu", roadName: "関越自動車道", isSmart: false, etcOnly: false, entranceAvailable: true, exitAvailable: true, area: "埼玉県深谷市", directionGroup: "shizuoka", prevIcId: "kanetsu_higashi_matsuyama", nextIcId: "kanetsu_honjo_kodama", availableHours: "24h", geocodeQuery: "花園インターチェンジ 関越自動車道" },
  { id: "kanetsu_honjo_kodama", name: "本庄児玉IC", roadId: "kanetsu", roadName: "関越自動車道", isSmart: false, etcOnly: false, entranceAvailable: true, exitAvailable: true, area: "埼玉県本庄市", directionGroup: "shizuoka", prevIcId: "kanetsu_hanazono", availableHours: "24h", geocodeQuery: "本庄児玉インターチェンジ 関越自動車道" },
  { id: "kanetsu_takasaki", name: "高崎IC", roadId: "kanetsu", roadName: "関越自動車道", isSmart: false, etcOnly: false, entranceAvailable: true, exitAvailable: true, area: "群馬県高崎市", directionGroup: "shizuoka", availableHours: "24h", geocodeQuery: "高崎インターチェンジ 関越自動車道" },
  { id: "kanetsu_maebashi", name: "前橋IC", roadId: "kanetsu", roadName: "関越自動車道", isSmart: false, etcOnly: false, entranceAvailable: true, exitAvailable: true, area: "群馬県前橋市", directionGroup: "shizuoka", availableHours: "24h", geocodeQuery: "前橋インターチェンジ 関越自動車道" },
  { id: "kanetsu_shibukawa_ikaho", name: "渋川伊香保IC", roadId: "kanetsu", roadName: "関越自動車道", isSmart: false, etcOnly: false, entranceAvailable: true, exitAvailable: true, area: "群馬県渋川市", directionGroup: "shizuoka", availableHours: "24h", geocodeQuery: "渋川伊香保インターチェンジ 関越自動車道" },
  { id: "kanetsu_tsukiyono", name: "月夜野IC", roadId: "kanetsu", roadName: "関越自動車道", isSmart: false, etcOnly: false, entranceAvailable: true, exitAvailable: true, area: "群馬県みなかみ町", directionGroup: "shizuoka", availableHours: "24h", geocodeQuery: "月夜野インターチェンジ 関越自動車道 みなかみ町" },
  { id: "kanetsu_yuzawa", name: "湯沢IC", roadId: "kanetsu", roadName: "関越自動車道", isSmart: false, etcOnly: false, entranceAvailable: true, exitAvailable: true, area: "新潟県湯沢町", directionGroup: "shizuoka", availableHours: "24h", geocodeQuery: "湯沢インターチェンジ 関越自動車道 新潟県" },
  { id: "kanetsu_ojiya", name: "小千谷IC", roadId: "kanetsu", roadName: "関越自動車道", isSmart: false, etcOnly: false, entranceAvailable: true, exitAvailable: true, area: "新潟県小千谷市", directionGroup: "shizuoka", availableHours: "24h", geocodeQuery: "小千谷インターチェンジ 関越自動車道" },
  { id: "kanetsu_nagaoka", name: "長岡IC", roadId: "kanetsu", roadName: "関越自動車道", isSmart: false, etcOnly: false, entranceAvailable: true, exitAvailable: true, area: "新潟県長岡市", directionGroup: "shizuoka", availableHours: "24h", geocodeQuery: "長岡インターチェンジ 関越自動車道 新潟県" },

  // ========== 東京外環自動車道 ==========
  { id: "gaikan_oizumi", name: "大泉IC", roadId: "gaikan", roadName: "東京外環自動車道", isSmart: false, etcOnly: false, entranceAvailable: true, exitAvailable: true, area: "東京都練馬区", directionGroup: "shizuoka", nextIcId: "gaikan_wako", availableHours: "24h", geocodeQuery: "大泉インターチェンジ 東京外環自動車道" },
  { id: "gaikan_wako", name: "和光IC", roadId: "gaikan", roadName: "東京外環自動車道", isSmart: false, etcOnly: false, entranceAvailable: true, exitAvailable: true, area: "埼玉県和光市", directionGroup: "shizuoka", prevIcId: "gaikan_oizumi", nextIcId: "gaikan_kawaguchi_nishi", availableHours: "24h", geocodeQuery: "和光インターチェンジ 東京外環自動車道" },
  { id: "gaikan_kawaguchi_nishi", name: "川口西IC", roadId: "gaikan", roadName: "東京外環自動車道", isSmart: false, etcOnly: false, entranceAvailable: true, exitAvailable: true, area: "埼玉県川口市", directionGroup: "shizuoka", prevIcId: "gaikan_wako", nextIcId: "gaikan_misato", availableHours: "24h", geocodeQuery: "川口西インターチェンジ 東京外環自動車道" },
  { id: "gaikan_misato", name: "三郷IC", roadId: "gaikan", roadName: "東京外環自動車道", isSmart: false, etcOnly: false, entranceAvailable: true, exitAvailable: true, area: "埼玉県三郷市", directionGroup: "shizuoka", prevIcId: "gaikan_kawaguchi_nishi", availableHours: "24h", geocodeQuery: "三郷インターチェンジ 東京外環自動車道" },
  { id: "gaikan_misato_minami", name: "三郷南IC", roadId: "gaikan", roadName: "東京外環自動車道", isSmart: false, etcOnly: false, entranceAvailable: true, exitAvailable: true, area: "埼玉県三郷市", directionGroup: "shizuoka", availableHours: "24h", geocodeQuery: "三郷南インターチェンジ 東京外環自動車道" },
  { id: "gaikan_ichikawa_kita", name: "市川北IC", roadId: "gaikan", roadName: "東京外環自動車道", isSmart: false, etcOnly: false, entranceAvailable: true, exitAvailable: true, area: "千葉県市川市", directionGroup: "shizuoka", availableHours: "24h", geocodeQuery: "市川北インターチェンジ 東京外環自動車道" },
  { id: "gaikan_matsudo", name: "松戸IC", roadId: "gaikan", roadName: "東京外環自動車道", isSmart: false, etcOnly: false, entranceAvailable: true, exitAvailable: true, area: "千葉県松戸市", directionGroup: "shizuoka", availableHours: "24h", geocodeQuery: "松戸インターチェンジ 東京外環自動車道" },

  // ========== 中央自動車道 ==========
  { id: "chuo_takaido", name: "高井戸IC", roadId: "chuo", roadName: "中央自動車道", isSmart: false, etcOnly: false, entranceAvailable: true, exitAvailable: true, area: "東京都杉並区", directionGroup: "shizuoka", nextIcId: "chuo_chofu", availableHours: "24h", notes: "中央自動車道の東京側起点", geocodeQuery: "高井戸インターチェンジ 中央自動車道" },
  { id: "chuo_chofu", name: "調布IC", roadId: "chuo", roadName: "中央自動車道", isSmart: false, etcOnly: false, entranceAvailable: true, exitAvailable: true, area: "東京都調布市", directionGroup: "shizuoka", prevIcId: "chuo_takaido", nextIcId: "chuo_kunitachi_fuchu", availableHours: "24h", geocodeQuery: "調布インターチェンジ 中央自動車道" },
  { id: "chuo_kunitachi_fuchu", name: "国立府中IC", roadId: "chuo", roadName: "中央自動車道", isSmart: false, etcOnly: false, entranceAvailable: true, exitAvailable: true, area: "東京都国立市", directionGroup: "shizuoka", prevIcId: "chuo_chofu", nextIcId: "chuo_hachioji", availableHours: "24h", geocodeQuery: "国立府中インターチェンジ 中央自動車道 東京都国立市" },
  { id: "chuo_hachioji", name: "八王子IC", roadId: "chuo", roadName: "中央自動車道", isSmart: false, etcOnly: false, entranceAvailable: true, exitAvailable: true, area: "東京都八王子市", directionGroup: "shizuoka", prevIcId: "chuo_kunitachi_fuchu", nextIcId: "chuo_sagamiko", availableHours: "24h", geocodeQuery: "八王子インターチェンジ 中央自動車道" },
  { id: "chuo_sagamiko", name: "相模湖IC", roadId: "chuo", roadName: "中央自動車道", isSmart: false, etcOnly: false, entranceAvailable: true, exitAvailable: true, area: "神奈川県相模原市", directionGroup: "shizuoka", prevIcId: "chuo_hachioji", nextIcId: "chuo_uenohara", availableHours: "24h", geocodeQuery: "相模湖インターチェンジ 中央自動車道 神奈川県相模原市緑区" },
  { id: "chuo_uenohara", name: "上野原IC", roadId: "chuo", roadName: "中央自動車道", isSmart: false, etcOnly: false, entranceAvailable: true, exitAvailable: true, area: "山梨県上野原市", directionGroup: "shizuoka", prevIcId: "chuo_sagamiko", nextIcId: "chuo_otsuki", availableHours: "24h", geocodeQuery: "上野原インターチェンジ 中央自動車道" },
  { id: "chuo_otsuki", name: "大月IC", roadId: "chuo", roadName: "中央自動車道", isSmart: false, etcOnly: false, entranceAvailable: true, exitAvailable: true, area: "山梨県大月市", directionGroup: "shizuoka", prevIcId: "chuo_uenohara", availableHours: "24h", geocodeQuery: "大月インターチェンジ 中央自動車道" },
  { id: "chuo_tsuru", name: "都留IC", roadId: "chuo", roadName: "中央自動車道", isSmart: false, etcOnly: false, entranceAvailable: true, exitAvailable: true, area: "山梨県都留市", directionGroup: "shizuoka", availableHours: "24h", geocodeQuery: "都留インターチェンジ 中央自動車道 山梨県" },
  { id: "chuo_kawaguchiko", name: "河口湖IC", roadId: "chuo", roadName: "中央自動車道", isSmart: false, etcOnly: false, entranceAvailable: true, exitAvailable: true, area: "山梨県富士河口湖町", directionGroup: "shizuoka", availableHours: "24h", geocodeQuery: "河口湖インターチェンジ 中央自動車道" },
  { id: "chuo_katsunuma", name: "勝沼IC", roadId: "chuo", roadName: "中央自動車道", isSmart: false, etcOnly: false, entranceAvailable: true, exitAvailable: true, area: "山梨県甲州市", directionGroup: "shizuoka", availableHours: "24h", geocodeQuery: "勝沼インターチェンジ 中央自動車道" },
  { id: "chuo_kofu_minami", name: "甲府南IC", roadId: "chuo", roadName: "中央自動車道", isSmart: false, etcOnly: false, entranceAvailable: true, exitAvailable: true, area: "山梨県甲府市", directionGroup: "shizuoka", availableHours: "24h", geocodeQuery: "甲府南インターチェンジ 中央自動車道" },
  { id: "chuo_kofu_showa", name: "甲府昭和IC", roadId: "chuo", roadName: "中央自動車道", isSmart: false, etcOnly: false, entranceAvailable: true, exitAvailable: true, area: "山梨県中巨摩郡昭和町", directionGroup: "shizuoka", availableHours: "24h", geocodeQuery: "甲府昭和インターチェンジ 中央自動車道" },
  { id: "chuo_nirasaki", name: "韮崎IC", roadId: "chuo", roadName: "中央自動車道", isSmart: false, etcOnly: false, entranceAvailable: true, exitAvailable: true, area: "山梨県韮崎市", directionGroup: "shizuoka", availableHours: "24h", geocodeQuery: "韮崎インターチェンジ 中央自動車道" },
  { id: "chuo_nagasaka", name: "長坂IC", roadId: "chuo", roadName: "中央自動車道", isSmart: false, etcOnly: false, entranceAvailable: true, exitAvailable: true, area: "山梨県北杜市", directionGroup: "shizuoka", availableHours: "24h", geocodeQuery: "長坂インターチェンジ 中央自動車道 北杜市" },
  { id: "chuo_kobuchizawa", name: "小淵沢IC", roadId: "chuo", roadName: "中央自動車道", isSmart: false, etcOnly: false, entranceAvailable: true, exitAvailable: true, area: "山梨県北杜市", directionGroup: "shizuoka", availableHours: "24h", geocodeQuery: "小淵沢インターチェンジ 中央自動車道" },
  { id: "chuo_suwa_minami", name: "諏訪南IC", roadId: "chuo", roadName: "中央自動車道", isSmart: false, etcOnly: false, entranceAvailable: true, exitAvailable: true, area: "長野県諏訪郡富士見町", directionGroup: "shizuoka", availableHours: "24h", geocodeQuery: "諏訪南インターチェンジ 中央自動車道 富士見町" },
  { id: "chuo_suwa", name: "諏訪IC", roadId: "chuo", roadName: "中央自動車道", isSmart: false, etcOnly: false, entranceAvailable: true, exitAvailable: true, area: "長野県岡谷市", directionGroup: "shizuoka", availableHours: "24h", geocodeQuery: "諏訪インターチェンジ 中央自動車道 岡谷市" },
  { id: "chuo_shiojiri", name: "塩尻IC", roadId: "chuo", roadName: "中央自動車道", isSmart: false, etcOnly: false, entranceAvailable: true, exitAvailable: true, area: "長野県塩尻市", directionGroup: "shizuoka", availableHours: "24h", geocodeQuery: "塩尻インターチェンジ 中央自動車道" },
  { id: "chuo_matsumoto", name: "松本IC", roadId: "chuo", roadName: "中央自動車道", isSmart: false, etcOnly: false, entranceAvailable: true, exitAvailable: true, area: "長野県松本市", directionGroup: "shizuoka", availableHours: "24h", geocodeQuery: "松本インターチェンジ 長野自動車道 松本市" },

  // ========== 圏央道（首都圏中央連絡自動車道）==========
  { id: "kenodo_akiruno", name: "あきる野IC", roadId: "kenodo", roadName: "首都圏中央連絡自動車道", isSmart: false, etcOnly: false, entranceAvailable: true, exitAvailable: true, area: "東京都あきる野市", directionGroup: "shizuoka", nextIcId: "kenodo_hanno", availableHours: "24h", geocodeQuery: "あきる野インターチェンジ 圏央道" },
  { id: "kenodo_hanno", name: "狭山日高IC", roadId: "kenodo", roadName: "首都圏中央連絡自動車道", isSmart: false, etcOnly: false, entranceAvailable: true, exitAvailable: true, area: "埼玉県日高市", directionGroup: "shizuoka", prevIcId: "kenodo_akiruno", nextIcId: "kenodo_iruma", availableHours: "24h", geocodeQuery: "狭山日高インターチェンジ 圏央道" },
  { id: "kenodo_iruma", name: "入間IC", roadId: "kenodo", roadName: "首都圏中央連絡自動車道", isSmart: false, etcOnly: false, entranceAvailable: true, exitAvailable: true, area: "埼玉県入間市", directionGroup: "shizuoka", prevIcId: "kenodo_hanno", nextIcId: "kenodo_kawashima", availableHours: "24h", geocodeQuery: "入間インターチェンジ 圏央道" },
  { id: "kenodo_kawashima", name: "川島IC", roadId: "kenodo", roadName: "首都圏中央連絡自動車道", isSmart: false, etcOnly: false, entranceAvailable: true, exitAvailable: true, area: "埼玉県比企郡川島町", directionGroup: "shizuoka", prevIcId: "kenodo_iruma", nextIcId: "kenodo_okegawa_kitamoto", availableHours: "24h", geocodeQuery: "川島インターチェンジ 圏央道" },
  { id: "kenodo_okegawa_kitamoto", name: "桶川北本IC", roadId: "kenodo", roadName: "首都圏中央連絡自動車道", isSmart: false, etcOnly: false, entranceAvailable: true, exitAvailable: true, area: "埼玉県桶川市", directionGroup: "shizuoka", prevIcId: "kenodo_kawashima", availableHours: "24h", geocodeQuery: "桶川北本インターチェンジ 圏央道" },

  // ========== 北陸自動車道 ==========
  { id: "hokuriku_maibara", name: "米原IC", roadId: "hokuriku", roadName: "北陸自動車道", isSmart: false, etcOnly: false, entranceAvailable: true, exitAvailable: true, area: "滋賀県米原市", directionGroup: "shizuoka", availableHours: "24h", geocodeQuery: "米原インターチェンジ 北陸自動車道 滋賀県" },
  { id: "hokuriku_nagahama", name: "長浜IC", roadId: "hokuriku", roadName: "北陸自動車道", isSmart: false, etcOnly: false, entranceAvailable: true, exitAvailable: true, area: "滋賀県長浜市", directionGroup: "shizuoka", availableHours: "24h", geocodeQuery: "長浜インターチェンジ 北陸自動車道" },
  { id: "hokuriku_kinomoto", name: "木之本IC", roadId: "hokuriku", roadName: "北陸自動車道", isSmart: false, etcOnly: false, entranceAvailable: true, exitAvailable: true, area: "滋賀県長浜市", directionGroup: "shizuoka", availableHours: "24h", geocodeQuery: "木之本インターチェンジ 北陸自動車道" },
  { id: "hokuriku_tsuruga", name: "敦賀IC", roadId: "hokuriku", roadName: "北陸自動車道", isSmart: false, etcOnly: false, entranceAvailable: true, exitAvailable: true, area: "福井県敦賀市", directionGroup: "shizuoka", availableHours: "24h", geocodeQuery: "敦賀インターチェンジ 北陸自動車道" },
  { id: "hokuriku_fukui", name: "福井IC", roadId: "hokuriku", roadName: "北陸自動車道", isSmart: false, etcOnly: false, entranceAvailable: true, exitAvailable: true, area: "福井県福井市", directionGroup: "shizuoka", availableHours: "24h", geocodeQuery: "福井インターチェンジ 北陸自動車道" },
  { id: "hokuriku_kaga", name: "加賀IC", roadId: "hokuriku", roadName: "北陸自動車道", isSmart: false, etcOnly: false, entranceAvailable: true, exitAvailable: true, area: "石川県加賀市", directionGroup: "shizuoka", availableHours: "24h", geocodeQuery: "加賀インターチェンジ 北陸自動車道" },
  { id: "hokuriku_komatsu", name: "小松IC", roadId: "hokuriku", roadName: "北陸自動車道", isSmart: false, etcOnly: false, entranceAvailable: true, exitAvailable: true, area: "石川県小松市", directionGroup: "shizuoka", availableHours: "24h", geocodeQuery: "小松インターチェンジ 北陸自動車道" },
  { id: "hokuriku_kanazawa_nishi", name: "金沢西IC", roadId: "hokuriku", roadName: "北陸自動車道", isSmart: false, etcOnly: false, entranceAvailable: true, exitAvailable: true, area: "石川県金沢市", directionGroup: "shizuoka", availableHours: "24h", geocodeQuery: "金沢西インターチェンジ 北陸自動車道" },
  { id: "hokuriku_kanazawa_higashi", name: "金沢東IC", roadId: "hokuriku", roadName: "北陸自動車道", isSmart: false, etcOnly: false, entranceAvailable: true, exitAvailable: true, area: "石川県金沢市", directionGroup: "shizuoka", availableHours: "24h", geocodeQuery: "金沢東インターチェンジ 北陸自動車道" },
  { id: "hokuriku_kanazawa_morimoto", name: "金沢森本IC", roadId: "hokuriku", roadName: "北陸自動車道", isSmart: false, etcOnly: false, entranceAvailable: true, exitAvailable: true, area: "石川県金沢市", directionGroup: "shizuoka", availableHours: "24h", geocodeQuery: "金沢森本インターチェンジ 北陸自動車道" },
  { id: "hokuriku_toyama", name: "富山IC", roadId: "hokuriku", roadName: "北陸自動車道", isSmart: false, etcOnly: false, entranceAvailable: true, exitAvailable: true, area: "富山県富山市", directionGroup: "shizuoka", availableHours: "24h", geocodeQuery: "富山インターチェンジ 北陸自動車道" },
  { id: "hokuriku_namerikawa", name: "滑川IC", roadId: "hokuriku", roadName: "北陸自動車道", isSmart: false, etcOnly: false, entranceAvailable: true, exitAvailable: true, area: "富山県滑川市", directionGroup: "shizuoka", availableHours: "24h", geocodeQuery: "滑川インターチェンジ 北陸自動車道" },
  { id: "hokuriku_uozu", name: "魚津IC", roadId: "hokuriku", roadName: "北陸自動車道", isSmart: false, etcOnly: false, entranceAvailable: true, exitAvailable: true, area: "富山県魚津市", directionGroup: "shizuoka", availableHours: "24h", geocodeQuery: "魚津インターチェンジ 北陸自動車道" },
  { id: "hokuriku_kurobe", name: "黒部IC", roadId: "hokuriku", roadName: "北陸自動車道", isSmart: false, etcOnly: false, entranceAvailable: true, exitAvailable: true, area: "富山県黒部市", directionGroup: "shizuoka", availableHours: "24h", geocodeQuery: "黒部インターチェンジ 北陸自動車道" },
  { id: "hokuriku_itoigawa", name: "糸魚川IC", roadId: "hokuriku", roadName: "北陸自動車道", isSmart: false, etcOnly: false, entranceAvailable: true, exitAvailable: true, area: "新潟県糸魚川市", directionGroup: "shizuoka", availableHours: "24h", geocodeQuery: "糸魚川インターチェンジ 北陸自動車道" },
  { id: "hokuriku_joetsu", name: "上越IC", roadId: "hokuriku", roadName: "北陸自動車道", isSmart: false, etcOnly: false, entranceAvailable: true, exitAvailable: true, area: "新潟県上越市", directionGroup: "shizuoka", availableHours: "24h", geocodeQuery: "上越インターチェンジ 北陸自動車道 新潟県" },
  { id: "hokuriku_nagaoka_jct", name: "長岡JCT", roadId: "hokuriku", roadName: "北陸自動車道", isSmart: false, etcOnly: false, entranceAvailable: true, exitAvailable: true, area: "新潟県長岡市", directionGroup: "shizuoka", availableHours: "24h", geocodeQuery: "長岡ジャンクション 北陸自動車道 関越自動車道" },
  { id: "hokuriku_sanjo_tsubame", name: "三条燕IC", roadId: "hokuriku", roadName: "北陸自動車道", isSmart: false, etcOnly: false, entranceAvailable: true, exitAvailable: true, area: "新潟県三条市", directionGroup: "shizuoka", availableHours: "24h", geocodeQuery: "三条燕インターチェンジ 北陸自動車道" },
  { id: "hokuriku_niigata_nishi", name: "新潟西IC", roadId: "hokuriku", roadName: "北陸自動車道", isSmart: false, etcOnly: false, entranceAvailable: true, exitAvailable: true, area: "新潟県新潟市", directionGroup: "shizuoka", availableHours: "24h", geocodeQuery: "新潟西インターチェンジ 北陸自動車道" },
  { id: "hokuriku_niigata", name: "新潟IC", roadId: "hokuriku", roadName: "北陸自動車道", isSmart: false, etcOnly: false, entranceAvailable: true, exitAvailable: true, area: "新潟県新潟市", directionGroup: "shizuoka", availableHours: "24h", geocodeQuery: "新潟インターチェンジ 北陸自動車道" },

  // ========== 常磐自動車道（南→北 順）==========
  { id: "joban_nagareyama", name: "流山IC", roadId: "joban", roadName: "常磐自動車道", isSmart: false, etcOnly: false, entranceAvailable: true, exitAvailable: true, area: "千葉県流山市", directionGroup: "shizuoka", nextIcId: "joban_kashiwa", junctionPrevIcId: "gaikan_misato", availableHours: "24h", notes: "常磐道の南端、三郷JCTで外環/首都高接続", geocodeQuery: "流山インターチェンジ 常磐自動車道" },
  { id: "joban_kashiwa", name: "柏IC", roadId: "joban", roadName: "常磐自動車道", isSmart: false, etcOnly: false, entranceAvailable: true, exitAvailable: true, area: "千葉県柏市", directionGroup: "shizuoka", prevIcId: "joban_nagareyama", nextIcId: "joban_tsuchiura_kita", availableHours: "24h", geocodeQuery: "柏インターチェンジ 常磐自動車道" },
  { id: "joban_tsuchiura_kita", name: "土浦北IC", roadId: "joban", roadName: "常磐自動車道", isSmart: false, etcOnly: false, entranceAvailable: true, exitAvailable: true, area: "茨城県土浦市", directionGroup: "shizuoka", prevIcId: "joban_kashiwa", nextIcId: "joban_mito", availableHours: "24h", geocodeQuery: "土浦北インターチェンジ 常磐自動車道" },
  { id: "joban_mito", name: "水戸IC", roadId: "joban", roadName: "常磐自動車道", isSmart: false, etcOnly: false, entranceAvailable: true, exitAvailable: true, area: "茨城県水戸市", directionGroup: "shizuoka", prevIcId: "joban_tsuchiura_kita", nextIcId: "joban_hitachi_minami_ota", availableHours: "24h", geocodeQuery: "水戸インターチェンジ 常磐自動車道" },
  { id: "joban_hitachi_minami_ota", name: "日立南太田IC", roadId: "joban", roadName: "常磐自動車道", isSmart: false, etcOnly: false, entranceAvailable: true, exitAvailable: true, area: "茨城県日立市", directionGroup: "shizuoka", prevIcId: "joban_mito", nextIcId: "joban_iwaki_chuo", availableHours: "24h", geocodeQuery: "日立南太田インターチェンジ 常磐自動車道" },
  { id: "joban_iwaki_chuo", name: "いわき中央IC", roadId: "joban", roadName: "常磐自動車道", isSmart: false, etcOnly: false, entranceAvailable: true, exitAvailable: true, area: "福島県いわき市", directionGroup: "shizuoka", prevIcId: "joban_hitachi_minami_ota", nextIcId: "joban_soma", junctionNextIcId: "banetsu_iwaki_miwa", availableHours: "24h", notes: "いわきJCTで磐越道接続", geocodeQuery: "いわき中央インターチェンジ 常磐自動車道" },
  { id: "joban_soma", name: "相馬IC", roadId: "joban", roadName: "常磐自動車道", isSmart: false, etcOnly: false, entranceAvailable: true, exitAvailable: true, area: "福島県相馬市", directionGroup: "shizuoka", prevIcId: "joban_iwaki_chuo", nextIcId: "joban_watari", availableHours: "24h", geocodeQuery: "相馬インターチェンジ 常磐自動車道" },
  { id: "joban_watari", name: "亘理IC", roadId: "joban", roadName: "常磐自動車道", isSmart: false, etcOnly: false, entranceAvailable: true, exitAvailable: true, area: "宮城県亘理郡亘理町", directionGroup: "shizuoka", prevIcId: "joban_soma", nextIcId: "joban_sendai_higashi", availableHours: "24h", geocodeQuery: "亘理インターチェンジ 常磐自動車道" },
  { id: "joban_sendai_higashi", name: "仙台東IC", roadId: "joban", roadName: "常磐自動車道", isSmart: false, etcOnly: false, entranceAvailable: true, exitAvailable: true, area: "宮城県仙台市宮城野区", directionGroup: "shizuoka", prevIcId: "joban_watari", availableHours: "24h", notes: "常磐道の北端、仙台若林JCT付近", geocodeQuery: "仙台東インターチェンジ 常磐自動車道" },

  // ========== 磐越自動車道（東いわきJCT→西新潟中央JCT 順）==========
  { id: "banetsu_iwaki_miwa", name: "いわき三和IC", roadId: "banetsu", roadName: "磐越自動車道", isSmart: false, etcOnly: false, entranceAvailable: true, exitAvailable: true, area: "福島県いわき市", directionGroup: "shizuoka", nextIcId: "banetsu_ono", junctionPrevIcId: "joban_iwaki_chuo", availableHours: "24h", notes: "磐越道の東端、いわきJCTで常磐道接続", geocodeQuery: "いわき三和インターチェンジ 磐越自動車道" },
  { id: "banetsu_ono", name: "小野IC", roadId: "banetsu", roadName: "磐越自動車道", isSmart: false, etcOnly: false, entranceAvailable: true, exitAvailable: true, area: "福島県田村郡小野町", directionGroup: "shizuoka", prevIcId: "banetsu_iwaki_miwa", nextIcId: "banetsu_funehiki_miharu", availableHours: "24h", geocodeQuery: "小野インターチェンジ 磐越自動車道" },
  { id: "banetsu_funehiki_miharu", name: "船引三春IC", roadId: "banetsu", roadName: "磐越自動車道", isSmart: false, etcOnly: false, entranceAvailable: true, exitAvailable: true, area: "福島県田村市", directionGroup: "shizuoka", prevIcId: "banetsu_ono", nextIcId: "banetsu_koriyama_higashi", availableHours: "24h", geocodeQuery: "船引三春インターチェンジ 磐越自動車道" },
  { id: "banetsu_koriyama_higashi", name: "郡山東IC", roadId: "banetsu", roadName: "磐越自動車道", isSmart: false, etcOnly: false, entranceAvailable: true, exitAvailable: true, area: "福島県郡山市", directionGroup: "shizuoka", prevIcId: "banetsu_funehiki_miharu", nextIcId: "banetsu_bandai_atami", junctionPrevIcId: "tohoku_koriyama", availableHours: "24h", notes: "郡山JCTで東北道接続", geocodeQuery: "郡山東インターチェンジ 磐越自動車道" },
  { id: "banetsu_bandai_atami", name: "磐梯熱海IC", roadId: "banetsu", roadName: "磐越自動車道", isSmart: false, etcOnly: false, entranceAvailable: true, exitAvailable: true, area: "福島県郡山市", directionGroup: "shizuoka", prevIcId: "banetsu_koriyama_higashi", nextIcId: "banetsu_inawashiro_bandai_kogen", availableHours: "24h", geocodeQuery: "磐梯熱海インターチェンジ 磐越自動車道" },
  { id: "banetsu_inawashiro_bandai_kogen", name: "猪苗代磐梯高原IC", roadId: "banetsu", roadName: "磐越自動車道", isSmart: false, etcOnly: false, entranceAvailable: true, exitAvailable: true, area: "福島県耶麻郡猪苗代町", directionGroup: "shizuoka", prevIcId: "banetsu_bandai_atami", nextIcId: "banetsu_bandai_kawahigashi", availableHours: "24h", geocodeQuery: "猪苗代磐梯高原インターチェンジ 磐越自動車道" },
  { id: "banetsu_bandai_kawahigashi", name: "磐梯河東IC", roadId: "banetsu", roadName: "磐越自動車道", isSmart: false, etcOnly: false, entranceAvailable: true, exitAvailable: true, area: "福島県耶麻郡磐梯町", directionGroup: "shizuoka", prevIcId: "banetsu_inawashiro_bandai_kogen", nextIcId: "banetsu_aizu_wakamatsu", availableHours: "24h", geocodeQuery: "磐梯河東インターチェンジ 磐越自動車道" },
  { id: "banetsu_aizu_wakamatsu", name: "会津若松IC", roadId: "banetsu", roadName: "磐越自動車道", isSmart: false, etcOnly: false, entranceAvailable: true, exitAvailable: true, area: "福島県会津若松市", directionGroup: "shizuoka", prevIcId: "banetsu_bandai_kawahigashi", nextIcId: "banetsu_aizu_bange", availableHours: "24h", geocodeQuery: "会津若松インターチェンジ 磐越自動車道" },
  { id: "banetsu_aizu_bange", name: "会津坂下IC", roadId: "banetsu", roadName: "磐越自動車道", isSmart: false, etcOnly: false, entranceAvailable: true, exitAvailable: true, area: "福島県河沼郡会津坂下町", directionGroup: "shizuoka", prevIcId: "banetsu_aizu_wakamatsu", nextIcId: "banetsu_nishi_aizu", availableHours: "24h", geocodeQuery: "会津坂下インターチェンジ 磐越自動車道" },
  { id: "banetsu_nishi_aizu", name: "西会津IC", roadId: "banetsu", roadName: "磐越自動車道", isSmart: false, etcOnly: false, entranceAvailable: true, exitAvailable: true, area: "福島県耶麻郡西会津町", directionGroup: "shizuoka", prevIcId: "banetsu_aizu_bange", nextIcId: "banetsu_tsugawa", availableHours: "24h", geocodeQuery: "西会津インターチェンジ 磐越自動車道" },
  { id: "banetsu_tsugawa", name: "津川IC", roadId: "banetsu", roadName: "磐越自動車道", isSmart: false, etcOnly: false, entranceAvailable: true, exitAvailable: true, area: "新潟県東蒲原郡阿賀町", directionGroup: "shizuoka", prevIcId: "banetsu_nishi_aizu", nextIcId: "banetsu_mikawa", availableHours: "24h", geocodeQuery: "津川インターチェンジ 磐越自動車道" },
  { id: "banetsu_mikawa", name: "三川IC", roadId: "banetsu", roadName: "磐越自動車道", isSmart: false, etcOnly: false, entranceAvailable: true, exitAvailable: true, area: "新潟県東蒲原郡阿賀町", directionGroup: "shizuoka", prevIcId: "banetsu_tsugawa", nextIcId: "banetsu_yasuda", availableHours: "24h", geocodeQuery: "三川インターチェンジ 磐越自動車道" },
  { id: "banetsu_yasuda", name: "安田IC", roadId: "banetsu", roadName: "磐越自動車道", isSmart: false, etcOnly: false, entranceAvailable: true, exitAvailable: true, area: "新潟県阿賀野市", directionGroup: "shizuoka", prevIcId: "banetsu_mikawa", availableHours: "24h", notes: "磐越道の西端付近、新潟中央JCTで北陸道接続", geocodeQuery: "安田インターチェンジ 磐越自動車道" },

  // ========== 東関東自動車道 ==========
  { id: "higashikanto_ichikawa", name: "市川IC", roadId: "higashikanto", roadName: "東関東自動車道", isSmart: false, etcOnly: false, entranceAvailable: true, exitAvailable: true, area: "千葉県市川市", directionGroup: "shizuoka", availableHours: "24h", geocodeQuery: "市川インターチェンジ 東関東自動車道" },
  { id: "higashikanto_chiba_kita", name: "千葉北IC", roadId: "higashikanto", roadName: "東関東自動車道", isSmart: false, etcOnly: false, entranceAvailable: true, exitAvailable: true, area: "千葉県千葉市花見川区", directionGroup: "shizuoka", availableHours: "24h", geocodeQuery: "千葉北インターチェンジ 東関東自動車道" },
  { id: "higashikanto_yotsukaido", name: "四街道IC", roadId: "higashikanto", roadName: "東関東自動車道", isSmart: false, etcOnly: false, entranceAvailable: true, exitAvailable: true, area: "千葉県四街道市", directionGroup: "shizuoka", availableHours: "24h", geocodeQuery: "四街道インターチェンジ 東関東自動車道" },
  { id: "higashikanto_narita", name: "成田IC", roadId: "higashikanto", roadName: "東関東自動車道", isSmart: false, etcOnly: false, entranceAvailable: true, exitAvailable: true, area: "千葉県成田市", directionGroup: "shizuoka", availableHours: "24h", geocodeQuery: "成田インターチェンジ 東関東自動車道" },

  // ========== 首都高速道路 ==========
  { id: "shuto_shiodome", name: "汐留IC", roadId: "shuto", roadName: "首都高速道路", isSmart: false, etcOnly: false, entranceAvailable: true, exitAvailable: true, area: "東京都港区", directionGroup: "shizuoka", availableHours: "24h", geocodeQuery: "首都高速道路 汐留出入口 東京都港区" },
  { id: "shuto_shiba", name: "芝公園IC", roadId: "shuto", roadName: "首都高速道路", isSmart: false, etcOnly: false, entranceAvailable: true, exitAvailable: true, area: "東京都港区", directionGroup: "shizuoka", availableHours: "24h", geocodeQuery: "首都高速道路 芝公園出入口 東京都港区" },
  { id: "shuto_kasumigaseki", name: "霞が関IC", roadId: "shuto", roadName: "首都高速道路", isSmart: false, etcOnly: false, entranceAvailable: true, exitAvailable: true, area: "東京都千代田区", directionGroup: "shizuoka", availableHours: "24h", geocodeQuery: "首都高速都心環状線 霞が関出口 千代田区" },
  { id: "shuto_shibuya", name: "渋谷IC", roadId: "shuto", roadName: "首都高速道路", isSmart: false, etcOnly: false, entranceAvailable: true, exitAvailable: true, area: "東京都渋谷区", directionGroup: "shizuoka", availableHours: "24h", geocodeQuery: "首都高速3号渋谷線 渋谷出入口 渋谷区" },
  { id: "shuto_sangenjaya", name: "三軒茶屋IC", roadId: "shuto", roadName: "首都高速道路", isSmart: false, etcOnly: false, entranceAvailable: true, exitAvailable: true, area: "東京都世田谷区", directionGroup: "shizuoka", availableHours: "24h", geocodeQuery: "首都高速3号渋谷線 三軒茶屋出入口 世田谷区" },
  { id: "shuto_yoga", name: "用賀IC", roadId: "shuto", roadName: "首都高速道路", isSmart: false, etcOnly: false, entranceAvailable: true, exitAvailable: true, area: "東京都世田谷区", directionGroup: "shizuoka", availableHours: "24h", geocodeQuery: "首都高速3号渋谷線 用賀出入口 世田谷区" },
  { id: "shuto_hatsutagaoka", name: "幡ヶ谷IC", roadId: "shuto", roadName: "首都高速道路", isSmart: false, etcOnly: false, entranceAvailable: true, exitAvailable: true, area: "東京都渋谷区", directionGroup: "shizuoka", availableHours: "24h", geocodeQuery: "首都高速4号新宿線 幡ヶ谷出入口 渋谷区" },
  { id: "shuto_eifuku", name: "永福IC", roadId: "shuto", roadName: "首都高速道路", isSmart: false, etcOnly: false, entranceAvailable: true, exitAvailable: true, area: "東京都杉並区", directionGroup: "shizuoka", availableHours: "24h", geocodeQuery: "首都高速4号新宿線 永福出入口 杉並区" },
  { id: "shuto_ikebukuro", name: "池袋IC", roadId: "shuto", roadName: "首都高速道路", isSmart: false, etcOnly: false, entranceAvailable: true, exitAvailable: true, area: "東京都豊島区", directionGroup: "shizuoka", availableHours: "24h", geocodeQuery: "首都高速5号池袋線 池袋出入口 豊島区" },
  { id: "shuto_oi", name: "大井IC", roadId: "shuto", roadName: "首都高速道路", isSmart: false, etcOnly: false, entranceAvailable: true, exitAvailable: true, area: "東京都品川区", directionGroup: "shizuoka", availableHours: "24h", geocodeQuery: "首都高速1号羽田線 大井出入口 品川区" },
  { id: "shuto_hakozaki", name: "箱崎IC", roadId: "shuto", roadName: "首都高速道路", isSmart: false, etcOnly: false, entranceAvailable: true, exitAvailable: true, area: "東京都中央区", directionGroup: "shizuoka", availableHours: "24h", geocodeQuery: "首都高速都心環状線 箱崎出入口 中央区" },
  { id: "shuto_mukojima", name: "向島IC", roadId: "shuto", roadName: "首都高速道路", isSmart: false, etcOnly: false, entranceAvailable: true, exitAvailable: true, area: "東京都墨田区", directionGroup: "shizuoka", availableHours: "24h", geocodeQuery: "首都高速6号向島線 向島出入口 墨田区" },
  { id: "shuto_haneda", name: "羽田IC", roadId: "shuto", roadName: "首都高速道路", isSmart: false, etcOnly: false, entranceAvailable: true, exitAvailable: true, area: "東京都大田区", directionGroup: "shizuoka", availableHours: "24h", geocodeQuery: "首都高速1号羽田線 羽田出入口 大田区" },
  { id: "shuto_kasai", name: "葛西IC", roadId: "shuto", roadName: "首都高速道路", isSmart: false, etcOnly: false, entranceAvailable: true, exitAvailable: true, area: "東京都江戸川区", directionGroup: "shizuoka", availableHours: "24h", geocodeQuery: "首都高速湾岸線 葛西出入口 江戸川区" },
  { id: "shuto_ariake", name: "有明IC", roadId: "shuto", roadName: "首都高速道路", isSmart: false, etcOnly: false, entranceAvailable: true, exitAvailable: true, area: "東京都江東区", directionGroup: "shizuoka", availableHours: "24h", geocodeQuery: "首都高速湾岸線 有明出入口 江東区" },
  { id: "shuto_ikegami", name: "生麦IC", roadId: "shuto", roadName: "首都高速道路", isSmart: false, etcOnly: false, entranceAvailable: true, exitAvailable: true, area: "神奈川県横浜市鶴見区", directionGroup: "shizuoka", availableHours: "24h", geocodeQuery: "首都高速神奈川1号横羽線 生麦出入口 横浜市鶴見区" },
  { id: "shuto_yokohama_ekimae", name: "横浜駅西口IC", roadId: "shuto", roadName: "首都高速道路", isSmart: false, etcOnly: false, entranceAvailable: true, exitAvailable: true, area: "神奈川県横浜市西区", directionGroup: "shizuoka", availableHours: "24h", geocodeQuery: "首都高速神奈川1号横羽線 横浜駅西口出入口" },
  { id: "shuto_hodogaya", name: "保土ヶ谷IC", roadId: "shuto", roadName: "首都高速道路", isSmart: false, etcOnly: false, entranceAvailable: true, exitAvailable: true, area: "神奈川県横浜市保土ヶ谷区", directionGroup: "shizuoka", availableHours: "24h", geocodeQuery: "首都高速神奈川3号狩場線 保土ヶ谷出入口 横浜市" },
  { id: "shuto_shin_yokohama", name: "新横浜IC", roadId: "shuto", roadName: "首都高速道路", isSmart: false, etcOnly: false, entranceAvailable: true, exitAvailable: true, area: "神奈川県横浜市港北区", directionGroup: "shizuoka", availableHours: "24h", geocodeQuery: "首都高速神奈川7号横浜北線 新横浜出入口" },

  // ========== 小田原厚木道路 ==========
  { id: "odawara_atsugi_atsugi", name: "厚木IC", roadId: "odawara_atsugi", roadName: "小田原厚木道路", isSmart: false, etcOnly: false, entranceAvailable: true, exitAvailable: true, area: "神奈川県厚木市", directionGroup: "shizuoka", nextIcId: "odawara_atsugi_isehara", availableHours: "24h", notes: "小田原厚木道路の東端。東名厚木ICに近接", geocodeQuery: "厚木インターチェンジ 小田原厚木道路" },
  { id: "odawara_atsugi_isehara", name: "伊勢原IC", roadId: "odawara_atsugi", roadName: "小田原厚木道路", isSmart: false, etcOnly: false, entranceAvailable: true, exitAvailable: true, area: "神奈川県伊勢原市", directionGroup: "shizuoka", prevIcId: "odawara_atsugi_atsugi", nextIcId: "odawara_atsugi_hiratsuka", availableHours: "24h", geocodeQuery: "伊勢原インターチェンジ 小田原厚木道路" },
  { id: "odawara_atsugi_hiratsuka", name: "平塚IC", roadId: "odawara_atsugi", roadName: "小田原厚木道路", isSmart: false, etcOnly: false, entranceAvailable: true, exitAvailable: true, area: "神奈川県平塚市", directionGroup: "shizuoka", prevIcId: "odawara_atsugi_isehara", nextIcId: "odawara_atsugi_odawara_higashi", availableHours: "24h", geocodeQuery: "平塚インターチェンジ 小田原厚木道路" },
  { id: "odawara_atsugi_odawara_higashi", name: "小田原東IC", roadId: "odawara_atsugi", roadName: "小田原厚木道路", isSmart: false, etcOnly: false, entranceAvailable: true, exitAvailable: true, area: "神奈川県小田原市", directionGroup: "shizuoka", prevIcId: "odawara_atsugi_hiratsuka", nextIcId: "odawara_atsugi_odawara", availableHours: "24h", geocodeQuery: "小田原東インターチェンジ 小田原厚木道路" },
  { id: "odawara_atsugi_odawara", name: "小田原IC", roadId: "odawara_atsugi", roadName: "小田原厚木道路", isSmart: false, etcOnly: false, entranceAvailable: true, exitAvailable: true, area: "神奈川県小田原市", directionGroup: "shizuoka", prevIcId: "odawara_atsugi_odawara_higashi", availableHours: "24h", notes: "小田原厚木道路の西端", geocodeQuery: "小田原インターチェンジ 小田原厚木道路" },

  // ========== 山形自動車道（村田JCT→鶴岡JCT 順）==========
  { id: "yamagata_miyagi_kawasaki", name: "宮城川崎IC", roadId: "yamagata", roadName: "山形自動車道", isSmart: false, etcOnly: false, entranceAvailable: true, exitAvailable: true, area: "宮城県柴田郡川崎町", directionGroup: "shizuoka", nextIcId: "yamagata_sasaya", junctionPrevIcId: "tohoku_sendai_minami", availableHours: "24h", notes: "山形道の東端、村田JCTで東北道接続", geocodeQuery: "宮城川崎インターチェンジ 山形自動車道" },
  { id: "yamagata_sasaya", name: "笹谷IC", roadId: "yamagata", roadName: "山形自動車道", isSmart: false, etcOnly: false, entranceAvailable: true, exitAvailable: true, area: "宮城県柴田郡川崎町", directionGroup: "shizuoka", prevIcId: "yamagata_miyagi_kawasaki", nextIcId: "yamagata_sekizawa", availableHours: "24h", geocodeQuery: "笹谷インターチェンジ 山形自動車道" },
  { id: "yamagata_sekizawa", name: "関沢IC", roadId: "yamagata", roadName: "山形自動車道", isSmart: false, etcOnly: false, entranceAvailable: true, exitAvailable: true, area: "山形県山形市", directionGroup: "shizuoka", prevIcId: "yamagata_sasaya", nextIcId: "yamagata_yamagata_zao", availableHours: "24h", geocodeQuery: "関沢インターチェンジ 山形自動車道" },
  { id: "yamagata_yamagata_zao", name: "山形蔵王IC", roadId: "yamagata", roadName: "山形自動車道", isSmart: false, etcOnly: false, entranceAvailable: true, exitAvailable: true, area: "山形県山形市", directionGroup: "shizuoka", prevIcId: "yamagata_sekizawa", nextIcId: "yamagata_yamagata_chuo", availableHours: "24h", geocodeQuery: "山形蔵王パーキングエリア 山形自動車道" },
  { id: "yamagata_yamagata_chuo", name: "山形中央IC", roadId: "yamagata", roadName: "山形自動車道", isSmart: false, etcOnly: false, entranceAvailable: true, exitAvailable: true, area: "山形県山形市", directionGroup: "shizuoka", prevIcId: "yamagata_yamagata_zao", nextIcId: "yamagata_yamagata_kita", availableHours: "24h", geocodeQuery: "山形中央インターチェンジ" },
  { id: "yamagata_yamagata_kita", name: "山形北IC", roadId: "yamagata", roadName: "山形自動車道", isSmart: false, etcOnly: false, entranceAvailable: true, exitAvailable: true, area: "山形県山形市", directionGroup: "shizuoka", prevIcId: "yamagata_yamagata_chuo", nextIcId: "yamagata_tendo", availableHours: "24h", geocodeQuery: "山形北インターチェンジ 山形自動車道" },
  { id: "yamagata_tendo", name: "天童IC", roadId: "yamagata", roadName: "山形自動車道", isSmart: false, etcOnly: false, entranceAvailable: true, exitAvailable: true, area: "山形県天童市", directionGroup: "shizuoka", prevIcId: "yamagata_yamagata_kita", nextIcId: "yamagata_tendo_kita", availableHours: "24h", geocodeQuery: "天童インターチェンジ 山形自動車道" },
  { id: "yamagata_tendo_kita", name: "天童北IC", roadId: "yamagata", roadName: "山形自動車道", isSmart: true, etcOnly: true, entranceAvailable: true, exitAvailable: true, area: "山形県天童市", directionGroup: "shizuoka", prevIcId: "yamagata_tendo", nextIcId: "yamagata_sakuranbo_higashine", availableHours: "24h", geocodeQuery: "天童北スマートインターチェンジ" },
  { id: "yamagata_sakuranbo_higashine", name: "さくらんぼ東根IC", roadId: "yamagata", roadName: "山形自動車道", isSmart: false, etcOnly: false, entranceAvailable: true, exitAvailable: true, area: "山形県東根市", directionGroup: "shizuoka", prevIcId: "yamagata_tendo_kita", nextIcId: "yamagata_higashine", availableHours: "24h", geocodeQuery: "さくらんぼ東根インターチェンジ" },
  { id: "yamagata_higashine", name: "東根IC", roadId: "yamagata", roadName: "山形自動車道", isSmart: false, etcOnly: false, entranceAvailable: true, exitAvailable: true, area: "山形県東根市", directionGroup: "shizuoka", prevIcId: "yamagata_sakuranbo_higashine", nextIcId: "yamagata_murayama", availableHours: "24h", geocodeQuery: "東根インターチェンジ 山形自動車道" },
  { id: "yamagata_murayama", name: "村山IC", roadId: "yamagata", roadName: "山形自動車道", isSmart: false, etcOnly: false, entranceAvailable: true, exitAvailable: true, area: "山形県村山市", directionGroup: "shizuoka", prevIcId: "yamagata_higashine", nextIcId: "yamagata_nishikawa", availableHours: "24h", geocodeQuery: "村山インターチェンジ 山形自動車道" },
  { id: "yamagata_nishikawa", name: "西川IC", roadId: "yamagata", roadName: "山形自動車道", isSmart: false, etcOnly: false, entranceAvailable: true, exitAvailable: true, area: "山形県西村山郡西川町", directionGroup: "shizuoka", prevIcId: "yamagata_murayama", nextIcId: "yamagata_gassan", availableHours: "24h", geocodeQuery: "西川インターチェンジ 山形自動車道" },
  { id: "yamagata_gassan", name: "月山IC", roadId: "yamagata", roadName: "山形自動車道", isSmart: false, etcOnly: false, entranceAvailable: true, exitAvailable: true, area: "山形県西村山郡西川町", directionGroup: "shizuoka", prevIcId: "yamagata_nishikawa", nextIcId: "yamagata_shonai_asahi", availableHours: "24h", geocodeQuery: "月山インターチェンジ 山形自動車道" },
  { id: "yamagata_shonai_asahi", name: "庄内あさひIC", roadId: "yamagata", roadName: "山形自動車道", isSmart: false, etcOnly: false, entranceAvailable: true, exitAvailable: true, area: "山形県鶴岡市", directionGroup: "shizuoka", prevIcId: "yamagata_gassan", nextIcId: "yamagata_tsuruoka", availableHours: "24h", geocodeQuery: "庄内あさひインターチェンジ" },
  { id: "yamagata_tsuruoka", name: "鶴岡IC", roadId: "yamagata", roadName: "山形自動車道", isSmart: false, etcOnly: false, entranceAvailable: true, exitAvailable: true, area: "山形県鶴岡市", directionGroup: "shizuoka", prevIcId: "yamagata_shonai_asahi", availableHours: "24h", notes: "山形道の西端", geocodeQuery: "鶴岡インターチェンジ 山形自動車道" },

  // ========== 東北中央自動車道（南福島→新庄方面）==========
  { id: "tohoku_chuo_fukushima_osasou", name: "福島大笹生IC", roadId: "tohoku_chuo", roadName: "東北中央自動車道", isSmart: false, etcOnly: false, entranceAvailable: true, exitAvailable: true, area: "福島県福島市", directionGroup: "shizuoka", nextIcId: "tohoku_chuo_yonezawa_kita", junctionPrevIcId: "tohoku_fukushima_nishi", availableHours: "24h", notes: "福島JCTで東北道接続", geocodeQuery: "福島大笹生インターチェンジ 東北中央自動車道" },
  { id: "tohoku_chuo_yonezawa_kita", name: "米沢北IC", roadId: "tohoku_chuo", roadName: "東北中央自動車道", isSmart: false, etcOnly: false, entranceAvailable: true, exitAvailable: true, area: "山形県米沢市", directionGroup: "shizuoka", prevIcId: "tohoku_chuo_fukushima_osasou", nextIcId: "tohoku_chuo_yonezawa_chuo", availableHours: "24h", geocodeQuery: "米沢北インターチェンジ 東北中央自動車道" },
  { id: "tohoku_chuo_yonezawa_chuo", name: "米沢中央IC", roadId: "tohoku_chuo", roadName: "東北中央自動車道", isSmart: false, etcOnly: false, entranceAvailable: true, exitAvailable: true, area: "山形県米沢市", directionGroup: "shizuoka", prevIcId: "tohoku_chuo_yonezawa_kita", nextIcId: "tohoku_chuo_nanyo_takahata", availableHours: "24h", geocodeQuery: "米沢中央インターチェンジ 東北中央自動車道" },
  { id: "tohoku_chuo_nanyo_takahata", name: "南陽高畠IC", roadId: "tohoku_chuo", roadName: "東北中央自動車道", isSmart: false, etcOnly: false, entranceAvailable: true, exitAvailable: true, area: "山形県東置賜郡高畠町", directionGroup: "shizuoka", prevIcId: "tohoku_chuo_yonezawa_chuo", nextIcId: "tohoku_chuo_kaminoyama", availableHours: "24h", geocodeQuery: "南陽高畠インターチェンジ 東北中央自動車道" },
  { id: "tohoku_chuo_kaminoyama", name: "山形上山IC", roadId: "tohoku_chuo", roadName: "東北中央自動車道", isSmart: false, etcOnly: false, entranceAvailable: true, exitAvailable: true, area: "山形県上山市", directionGroup: "shizuoka", prevIcId: "tohoku_chuo_nanyo_takahata", nextIcId: "tohoku_chuo_higashine_jct", junctionNextIcId: "yamagata_yamagata_chuo", availableHours: "24h", notes: "山形JCTで山形道接続", geocodeQuery: "山形上山インターチェンジ 東北中央自動車道" },
  { id: "tohoku_chuo_higashine_jct", name: "東根北IC", roadId: "tohoku_chuo", roadName: "東北中央自動車道", isSmart: false, etcOnly: false, entranceAvailable: true, exitAvailable: true, area: "山形県東根市", directionGroup: "shizuoka", prevIcId: "tohoku_chuo_kaminoyama", nextIcId: "tohoku_chuo_obanazawa", availableHours: "24h", geocodeQuery: "東根北インターチェンジ 東北中央自動車道" },
  { id: "tohoku_chuo_obanazawa", name: "尾花沢IC", roadId: "tohoku_chuo", roadName: "東北中央自動車道", isSmart: false, etcOnly: false, entranceAvailable: true, exitAvailable: true, area: "山形県尾花沢市", directionGroup: "shizuoka", prevIcId: "tohoku_chuo_higashine_jct", nextIcId: "tohoku_chuo_shinjo", availableHours: "24h", geocodeQuery: "尾花沢インターチェンジ 東北中央自動車道" },
  { id: "tohoku_chuo_shinjo", name: "新庄IC", roadId: "tohoku_chuo", roadName: "東北中央自動車道", isSmart: false, etcOnly: false, entranceAvailable: true, exitAvailable: true, area: "山形県新庄市", directionGroup: "shizuoka", prevIcId: "tohoku_chuo_obanazawa", availableHours: "24h", notes: "東北中央道の北端", geocodeQuery: "新庄インターチェンジ 東北中央自動車道" },

  // ========== 上信越自動車道（藤岡JCT→上越JCT 順）==========
  { id: "joshinetsu_fujioka", name: "藤岡IC", roadId: "joshinetsu", roadName: "上信越自動車道", isSmart: false, etcOnly: false, entranceAvailable: true, exitAvailable: true, area: "群馬県藤岡市", directionGroup: "shizuoka", nextIcId: "joshinetsu_yoshii", junctionPrevIcId: "kanetsu_takasaki", availableHours: "24h", notes: "上信越道の南端、藤岡JCTで関越道接続", geocodeQuery: "藤岡インターチェンジ 上信越自動車道" },
  { id: "joshinetsu_yoshii", name: "吉井IC", roadId: "joshinetsu", roadName: "上信越自動車道", isSmart: false, etcOnly: false, entranceAvailable: true, exitAvailable: true, area: "群馬県高崎市", directionGroup: "shizuoka", prevIcId: "joshinetsu_fujioka", nextIcId: "joshinetsu_tomioka", availableHours: "24h", geocodeQuery: "吉井インターチェンジ 上信越自動車道" },
  { id: "joshinetsu_tomioka", name: "富岡IC", roadId: "joshinetsu", roadName: "上信越自動車道", isSmart: false, etcOnly: false, entranceAvailable: true, exitAvailable: true, area: "群馬県富岡市", directionGroup: "shizuoka", prevIcId: "joshinetsu_yoshii", nextIcId: "joshinetsu_matsuida_myogi", availableHours: "24h", geocodeQuery: "富岡インターチェンジ 上信越自動車道" },
  { id: "joshinetsu_matsuida_myogi", name: "松井田妙義IC", roadId: "joshinetsu", roadName: "上信越自動車道", isSmart: false, etcOnly: false, entranceAvailable: true, exitAvailable: true, area: "群馬県安中市", directionGroup: "shizuoka", prevIcId: "joshinetsu_tomioka", nextIcId: "joshinetsu_usui_karuizawa", availableHours: "24h", geocodeQuery: "松井田妙義インターチェンジ 上信越自動車道" },
  { id: "joshinetsu_usui_karuizawa", name: "碓氷軽井沢IC", roadId: "joshinetsu", roadName: "上信越自動車道", isSmart: false, etcOnly: false, entranceAvailable: true, exitAvailable: true, area: "群馬県安中市", directionGroup: "shizuoka", prevIcId: "joshinetsu_matsuida_myogi", nextIcId: "joshinetsu_saku", availableHours: "24h", geocodeQuery: "碓氷軽井沢インターチェンジ 上信越自動車道" },
  { id: "joshinetsu_saku", name: "佐久IC", roadId: "joshinetsu", roadName: "上信越自動車道", isSmart: false, etcOnly: false, entranceAvailable: true, exitAvailable: true, area: "長野県佐久市", directionGroup: "shizuoka", prevIcId: "joshinetsu_usui_karuizawa", nextIcId: "joshinetsu_komoro", availableHours: "24h", geocodeQuery: "佐久インターチェンジ 上信越自動車道" },
  { id: "joshinetsu_komoro", name: "小諸IC", roadId: "joshinetsu", roadName: "上信越自動車道", isSmart: false, etcOnly: false, entranceAvailable: true, exitAvailable: true, area: "長野県小諸市", directionGroup: "shizuoka", prevIcId: "joshinetsu_saku", nextIcId: "joshinetsu_tobu_yunomaru", availableHours: "24h", geocodeQuery: "小諸インターチェンジ 上信越自動車道" },
  { id: "joshinetsu_tobu_yunomaru", name: "東部湯の丸IC", roadId: "joshinetsu", roadName: "上信越自動車道", isSmart: false, etcOnly: false, entranceAvailable: true, exitAvailable: true, area: "長野県東御市", directionGroup: "shizuoka", prevIcId: "joshinetsu_komoro", nextIcId: "joshinetsu_ueda_sugadaira", availableHours: "24h", geocodeQuery: "東部湯の丸インターチェンジ 上信越自動車道" },
  { id: "joshinetsu_ueda_sugadaira", name: "上田菅平IC", roadId: "joshinetsu", roadName: "上信越自動車道", isSmart: false, etcOnly: false, entranceAvailable: true, exitAvailable: true, area: "長野県上田市", directionGroup: "shizuoka", prevIcId: "joshinetsu_tobu_yunomaru", nextIcId: "joshinetsu_sakaki", availableHours: "24h", geocodeQuery: "上田菅平インターチェンジ 上信越自動車道" },
  { id: "joshinetsu_sakaki", name: "坂城IC", roadId: "joshinetsu", roadName: "上信越自動車道", isSmart: false, etcOnly: false, entranceAvailable: true, exitAvailable: true, area: "長野県埴科郡坂城町", directionGroup: "shizuoka", prevIcId: "joshinetsu_ueda_sugadaira", nextIcId: "joshinetsu_koshoku", availableHours: "24h", geocodeQuery: "坂城インターチェンジ 上信越自動車道" },
  { id: "joshinetsu_koshoku", name: "更埴IC", roadId: "joshinetsu", roadName: "上信越自動車道", isSmart: false, etcOnly: false, entranceAvailable: true, exitAvailable: true, area: "長野県千曲市", directionGroup: "shizuoka", prevIcId: "joshinetsu_sakaki", nextIcId: "joshinetsu_nagano", availableHours: "24h", notes: "更埴JCTで長野道接続", geocodeQuery: "更埴インターチェンジ 上信越自動車道" },
  { id: "joshinetsu_nagano", name: "長野IC", roadId: "joshinetsu", roadName: "上信越自動車道", isSmart: false, etcOnly: false, entranceAvailable: true, exitAvailable: true, area: "長野県長野市", directionGroup: "shizuoka", prevIcId: "joshinetsu_koshoku", nextIcId: "joshinetsu_susaka_nagano_higashi", availableHours: "24h", geocodeQuery: "長野インターチェンジ 上信越自動車道" },
  { id: "joshinetsu_susaka_nagano_higashi", name: "須坂長野東IC", roadId: "joshinetsu", roadName: "上信越自動車道", isSmart: false, etcOnly: false, entranceAvailable: true, exitAvailable: true, area: "長野県須坂市", directionGroup: "shizuoka", prevIcId: "joshinetsu_nagano", nextIcId: "joshinetsu_shinshu_nakano", availableHours: "24h", geocodeQuery: "須坂長野東インターチェンジ 上信越自動車道" },
  { id: "joshinetsu_shinshu_nakano", name: "信州中野IC", roadId: "joshinetsu", roadName: "上信越自動車道", isSmart: false, etcOnly: false, entranceAvailable: true, exitAvailable: true, area: "長野県中野市", directionGroup: "shizuoka", prevIcId: "joshinetsu_susaka_nagano_higashi", nextIcId: "joshinetsu_toyota_iiyama", availableHours: "24h", geocodeQuery: "信州中野インターチェンジ 上信越自動車道" },
  { id: "joshinetsu_toyota_iiyama", name: "豊田飯山IC", roadId: "joshinetsu", roadName: "上信越自動車道", isSmart: false, etcOnly: false, entranceAvailable: true, exitAvailable: true, area: "長野県中野市", directionGroup: "shizuoka", prevIcId: "joshinetsu_shinshu_nakano", nextIcId: "joshinetsu_myoko_kogen", availableHours: "24h", geocodeQuery: "豊田飯山インターチェンジ 上信越自動車道" },
  { id: "joshinetsu_myoko_kogen", name: "妙高高原IC", roadId: "joshinetsu", roadName: "上信越自動車道", isSmart: false, etcOnly: false, entranceAvailable: true, exitAvailable: true, area: "新潟県妙高市", directionGroup: "shizuoka", prevIcId: "joshinetsu_toyota_iiyama", nextIcId: "joshinetsu_joetsu_takada", availableHours: "24h", geocodeQuery: "妙高高原インターチェンジ 上信越自動車道" },
  { id: "joshinetsu_joetsu_takada", name: "上越高田IC", roadId: "joshinetsu", roadName: "上信越自動車道", isSmart: false, etcOnly: false, entranceAvailable: true, exitAvailable: true, area: "新潟県上越市", directionGroup: "shizuoka", prevIcId: "joshinetsu_myoko_kogen", nextIcId: "joshinetsu_joetsu", availableHours: "24h", geocodeQuery: "上越高田インターチェンジ 上信越自動車道" },
  { id: "joshinetsu_joetsu", name: "上越IC", roadId: "joshinetsu", roadName: "上信越自動車道", isSmart: false, etcOnly: false, entranceAvailable: true, exitAvailable: true, area: "新潟県上越市", directionGroup: "shizuoka", prevIcId: "joshinetsu_joetsu_takada", availableHours: "24h", notes: "上信越道の北端、上越JCTで北陸道接続", geocodeQuery: "上越インターチェンジ 上信越自動車道" },
];
